# Generated by Django 6.0.1 on 2026-01-17 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('urban', 'Urban Area'), ('rural', 'Rural Area'), ('coastal', 'Coastal Area'), ('hilly', 'Hilly/Mountainous Area')], max_length=20)),
                ('household_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('housing_type', models.CharField(choices=[('pucca', 'Pucca (Concrete/Brick)'), ('semi_pucca', 'Semi-Pucca'), ('kutcha', 'Kutcha (Mud/Temporary)'), ('apartment', 'Apartment/Flat')], max_length=20)),
                ('has_emergency_kit', models.BooleanField(default=False)),
                ('has_water_storage', models.BooleanField(default=False)),
                ('has_first_aid_knowledge', models.BooleanField(default=False)),
                ('past_disaster_experience', models.BooleanField(default=False)),
                ('self_rated_preparedness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('has_evacuation_plan', models.BooleanField(default=False)),
                ('knows_emergency_contacts', models.BooleanField(default=False)),
                ('preparedness_score', models.FloatField(default=0.0)),
                ('preparedness_level', models.CharField(choices=[('low', 'Low Preparedness'), ('medium', 'Medium Preparedness'), ('high', 'High Preparedness')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
